### ISSUE TITLE
Add remaining widgets to table cell selector

### ISSUE THREAD

**Issue by ray-millward-tessella** [dls-controls/malcolmjs#159]
Add the remaining widgets to the table cell control selector: checkbox, combobox and textinput.

These should all be demo'd with storybook.

**Comment by btester271828** [comment]
I have implemented a 'widgetSelector' which will pick & insert the required widget. However, there are some formatting issues; from the example I currently have in storybook it seems that textInput widgets take far more length than required (or allocated) when placed in tables.

**Comment by ray-millward-tessella** [comment]
Ok, we'll there's plenty of time left on this story so you've got some time to look into potential fixes.
