### ISSUE TITLE
Add a row changed event handler to the table

### ISSUE THREAD

**Issue by ray-millward-tessella** [dls-controls/malcolmjs#160]
Hook up a row changed event whenever one of the controls in the row updates that pushes out an updated for the entire row.

Note that this doesn't have to hook up to the entire system yet, it is sufficient to show that the event is fired in storybook

**Comment by btester271828** [comment]
Set up the table widget to expect a row change handler; this will be called by the widget (within widgetSelector) with the new value, the column label and the row number as arguments upon a change event.

**Comment by ray-millward-tessella** [comment]
Does this mean it will be the container components job to build the table row to send the update for? I guess that's not too bad as it will have the row number and we're planning to hold it as a 2D array.
