### ISSUE TITLE
Update the table components to have fixed or growing width

### ISSUE THREAD

**Issue by ray-millward-tessella** [dls-controls/malcolmjs#212]
We should add two classes of column components to tables so that certain widgets use a fixed width and other components are allowed to grow to fill the remaining space.

**Comment by btester271828** [comment]
Increased size estimate since this will require a significant reworking of the table component

**Comment by ray-millward-tessella** [comment]
This should also include sorting the scroll behaviour at the same time because these two problems are coupled
