### ISSUE TITLE
Investigate storing the archived values in shared browser memory

### ISSUE THREAD

**Issue by ray-millward-tessella** [dls-controls/malcolmjs#266]
In order to reduce the memory overhead with having multiple tabs open all recording attribute values, we should investigate if it is possible (using a library, etc) to store a part of the redux store in shared memory.

**Comment by btester271828** [comment]
The best way to achieve this would probably be to use the JS WebStorage API to store archive data as JSON strings (with a combination of the attribute path and timestamp or similar as the key). 
Tom suggested that each new window/tab should check in the local storage upon initial subscription to populate it's archive and then store all subsequent deltas in a circularBuffer in memory as per the current setup.
This would probably require a separate web worker to take charge of archiving the data work effectively, or perhaps the first window/tab to subscribe to a given attribute could be in charge of archiving that attribute to the local storage. This would seem to be too complex to consider working on now, but may be developed further in the future

**Comment by ray-millward-tessella** [comment]
Bryan and I had a good discussion about this and agreed it would have too much of a performance and security risk to it so we aren't going to take this further for now.
