### ISSUE TITLE
Sort out when the child panel should be visible

### ISSUE THREAD

**Issue by ray-millward-tessella** [dls-controls/malcolmjs#274]
There was a design discussion about the various situations when the child panel should be open or not, that information  was captured in a photo in the malcolmJS slack channel.

This story is about making the UI follow that table of situations.

**Comment by btester271828** [comment]
Clicking attribute name now closes the child panel (regardless of what it's contents is) when navigating to the new main attribute. We want the panel to stay open iff it is an attribute info panel

**Comment by ray-millward-tessella** [comment]
What should modify if right panel is open:
- [ ] click (not drag) block = open
- drag from palette = closes
- click on palette button = opens
- click on info icon = opens
- click on column heading = opens
- click on table/layout background = closes
- click on layout link = opens
- multi-select blocks = closes

Doesn't affect right panel:
- dragging block
- click on table row
- creating link
