### ISSUE TITLE
Investigate bug in Plotly when interacting during update

### ISSUE THREAD

**Issue by btester271828** [dls-controls/malcolmjs#284]
There is currently a bug in plotly.js which causes several error messages in the console and makes the plot become momentarily unresponsive if the user tries to interact (i.e pan or zoom) whilst and update of the plot is in progress. ( see https://github.com/plotly/plotly.js/issues/2644#issuecomment-391152782). We should see if we can mitigate the impact of this from our end

**Comment by btester271828** [comment]
Not sure if we want to mark this story as closed since we have implemented a work-around or leave it as open to remind us to check if the underlying bug gets fixed in future releases of plotyly?

**Comment by ray-millward-tessella** [comment]
I'm happy to close this if we have a workaround
