### ISSUE TITLE
Investigate main attribute behaviour on attribute widget focus

### ISSUE THREAD

**Issue by btester271828** [dls-controls/malcolmjs#285]
Currently, the only actions which change the main attribute are clicking on the alarm icon (which also opens the info pane) or clicking on the attribute's name in the relevant attributeDetails element (also clicking the view button for a table or flowgraph). We possibly want 'focusing' on a combobox or textinput to update the main attribute in some cases (i.e. when the info pane is open) but not all.

**Comment by ray-millward-tessella** [comment]
We don't want this behaviour
