### ISSUE TITLE
Scroll wheel doesn't work on firefox

### ISSUE THREAD

**Issue by thomascobb** [dls-controls/malcolmjs#305]
On RHEL6 and RHEL7 mouse button scroll is very very slow and the wrong way (mouse wheel up should be zoom in, like google maps)

**Comment by btester271828** [comment]
setting the inverseZoom prop works for reversing direction. The slowness appears to be due to firefox reporting scroll wheel delta in terms of lines instead of pixels (see https://github.com/esnet/react-timeseries-charts/issues/302) and react-diagrams not handling this properly

**Comment by ray-millward-tessella** [comment]
ok, is there anything we can do in the meantime? as it's kind of un-usable on Firefox. We might need to put the zoom buttons on as a workaround unless we can do something about the lines vs pixels issue.

**Comment by btester271828** [comment]
I've added an event handler to the div which wraps the layout which catches the event if it has deltaMode=DOM_DELTA_LINE and re-emits a new one with  deltaMode=DOM_DELTA_PIXELS
