### ISSUE TITLE
Display Block Attributes in a Pop-up Window

### ISSUE THREAD

**Issue by Kevin-Woods-Tessella** [dls-controls/malcolmjs#4]
As a controls engineer, I want to pop-up a window on screen to display a block, so that I can inspect the detailed attributes belonging to a block from a PandABox.

#### Acceptance Criteria
1. On entering the block URL, the pop-up window requests the block details from the PandAbox.
1. On receiving the block details, the pop-up window displays the block attributes.
   1. the pop-up window displays the block description in the summary panel
      1. if the block description is blank, the pop-up window should display "No description" in grayed-out text in the summary panel
   1. the pop-up window displays each attribute in a vertical column
      1. each row in the column consists of the attribute name, the attribute value and a status icon

#### Notes
1. The purpose of this user story is to get things started.  It will be refined with additional user stories.
1. The column of attributes can be a flat column for now.  Later we'll need to group the attributes.

**Comment by thomascobb** [comment]
This is superceded by the info panel
