### ISSUE TITLE
Reconnect to Malcolm fails

### ISSUE THREAD

**Issue by thomascobb** [dls-controls/malcolmjs#459]
Steps to reproduce:
* Malcolm4 branch.
* Navigate to http://localhost:8008/gui/DETECTOR/layout
* Stop server and wait for 20 seconds
* Browser console says:
```
socket disconnected  f0d2fd9fde0879bba50c.worker.js:1:19542
TypeError: this._socket.send is not a function  f0d2fd9fde0879bba50c.worker.js:1:56256
```
* Start server again
* Malcolmjs sits on a spinner forever

**Comment by btester271828** [comment]
Fixed in 1.7b1 release
