### ISSUE TITLE
Investigate if there is an integration with draw.io for sphinx

### ISSUE THREAD

**Issue by ray-millward-tessella** [dls-controls/malcolmjs#59]
We should see if there is an integration for sphinx that allows us to include the xml from draw.io directly in the rst rather than having to export the images.

**Comment by btester271828** [comment]
There seems to be no integration between sphinx and draw.io; however the best option seems to be to export as png from draw.io and check the "include a copy of my diagram" option. This embeds the xml data for the diagram into the png, so the file can be loaded back into draw.io and edited freely.
