### ISSUE TITLE
Check that our github releases key can't be used by others to release into the malcolmJS repo

### ISSUE THREAD

**Issue by ray-millward-tessella** [dls-controls/malcolmjs#63]
currently the travis script has a conditional release into our repo, we should check that if we fork into a different personal repo then we can't push up to the github releases for MalcolmJS

**Comment by btester271828** [comment]
Tested by forking MalcolmJS to personal GitHub. Travis will only deploy a release to the same repo which the commit/tag was pushed to.
![2018-05-02_travis_test.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ad74b136c49440014f1ff37/125516c66e82c728ace21e0d46bac4cb7bcfd3fcc2b9ed7cb04ff182205518672c17b7693cc7f33ab0487e021b4d44be44090c12fbf0dd78a2b26f74880d0bedd0385d74c66f10a5aa9e0dfd50e474d412dcfce9c85ecafa3f25ed8a8a4d3b16021b8efc5b3ca19e5985.png)

**Comment by ray-millward-tessella** [comment]
Can you try deleting the repo setting in .travis.yaml and see if it will let you.

**Comment by ray-millward-tessella** [comment]
Delete the repo bit from here
```
  on:
    repo: dls-controls/malcolmjs
    all_branches: true
    tags: true
```

**Comment by btester271828** [comment]
Tested;  removing repo bit from travis.yaml causes travis to throw Bad Credentials error on attempting deploy.

**Comment by ray-millward-tessella** [comment]
Great, ok this can be closed then
